### ISSUE TITLE
Question of the datasets

### ISSUE THREAD

**Issue by HorryChen** [Li-Wanhua/GR2N#2]
How to obtain the datasets required by this project, and whether to provide directly available datasets.

**Comment by Li-Wanhua** [comment]
Hi, Thanks for the interest. 

This paper used two datasets: PIPA and PISC. Since we are not contributors to these datasets, we have no right to disclose these datasets. But, you can directly consult the authors of these datasets and download the dataset.

If there are any problems in this process, maybe we can find a way to communicate privately, and I will try my best to solve your problem.

Again, we are not the owners of these datasets, so we have no right to disclose these datasets.

[1] PIPA: Sun, Q., Schiele, B., Fritz, M.: A domain based approach to social relation recognition. In: CVPR. pp. 3481–3490 (2017)
[2] PISC: Li, J., Wong, Y., Zhao, Q., Kankanhalli, M.S.: Dual-glance model for deciphering social relationships. In: ICCV. pp. 2650–2659 (2017)

**Comment by vampirely** [comment]
作者您好，我发现从这个项目代码运行出来的结果只有60%左右，代码里面
`cache_size = 256
if args.image_size == 448:
    cache_size = 256 * 2
if args.image_size == 352:
    cache_size = 402`   
上述这部分代码是否存在不公平问题？
还有一个问题就是您使用的数据集的索引能否提供一下，因为我发现公开的数据集里面并没有您在代码里面写的数据文件。

**Comment by vampirely** [comment]
> 作者您好，我发现从这个项目代码运行出来的结果只有60%左右，代码里面 `cache_size = 256 if args.image_size == 448: cache_size = 256 * 2 if args.image_size == 352: cache_size = 402` 上述这部分代码是否存在不公平问题？ 还有一个问题就是您使用的数据集的索引能否提供一下，因为我发现公开的数据集里面并没有您在代码里面写的数据文件。

忘了补充一下，是在PISC数据集上的结果

**Comment by Li-Wanhua** [comment]
This is a very common data augmentation operation. For example, when we train VGG-16/Resnet/Densenet, we first resize the image to 256 * 256, then crop the image to 224 * 224.  Here we use the exact same data augmentation operation: when the input size is 224, we perform random cropping from 256 to 224. When the input size is 448, we perform random cropping from 256 * 2 to 224 * 2.
Anyway, it's a very standard operation.

**Comment by vampirely** [comment]
> 

懂了，同时谢谢您的回复，我也是个新手，但是我在PISC上的结果跑出来只有0.60几左右，10个epoches，我不太清楚是怎么回事，因为我导师让我研究这个方向，所以您的代码对我很重要，我想知道为什么我出的结果的精度这么低。
